### ISSUE TITLE
Outdated or Invalid Plugin

### ISSUE THREAD

**Issue by jorea143** [AnthoDingo/DynmapSource#11]
It seems that this plugin is not loading on the latest rocket version. Please update it whenever you got time. Thank you.

**Comment by AnthoDingo** [comment]
Will fix it this week-end or this week. As soon as I've got time.

**Comment by jorea143** [comment]
Sounds great. Thank you.

**Comment by AnthoDingo** [comment]
New build available :
https://github.com/AnthoDingo/DynmapSource/releases/tag/2016-06-24
