### ISSUE TITLE
Dynmap outdated

### ISSUE THREAD

**Issue by Alec123445** [AnthoDingo/DynmapSource#12]
When I launch a server with Dynmap I get an error on start up
![image](https://cloud.githubusercontent.com/assets/18058634/16399457/67f90548-3c87-11e6-9db6-990f9a76570e.png)
Rocket had a major update breaking every plugin till update from plugin creators.

**Comment by msburgess3200** [comment]
Bump.

**Comment by Alec123445** [comment]
??

**Comment by AnthoDingo** [comment]
Have you tried this build : https://github.com/AnthoDingo/DynmapSource/releases/tag/2016-06-24 ?

**Comment by Alec123445** [comment]
Yes it works. Thanks

**Comment by msburgess3200** [comment]
No. It doesn't work.

`[loading] Dynmap
Dynmap >> Loading ...
Dynmap >> Finding map : C:\Users\root\Documents\Unturned Server Organiser\game\M
aps\Alpha Valley
Dynmap >> Finding map : C:\Users\root\Documents\Unturned Server Organiser\game\M
aps\Monolith
Dynmap >> Finding map : C:\Users\root\Documents\Unturned Server Organiser\game\M
aps\PEI
Dynmap >> Finding map : C:\Users\root\Documents\Unturned Server Organiser\game\M
aps\PEI Arena
Dynmap >> Finding map : C:\Users\root\Documents\Unturned Server Organiser\game\M
aps\Tutorial
Dynmap >> Finding map : C:\Users\root\Documents\Unturned Server Organiser\game\M
aps\Washington
Dynmap >> Finding map : C:\Users\root\Documents\Unturned Server Organiser\game\M
aps\Washington Arena
Dynmap >> Finding map : C:\Users\root\Documents\Unturned Server Organiser\game\M
aps\Yukon
Failed to load Dynmap, unloading now... :System.Net.WebException: Error: NameRes
olutionFailure
  at System.Net.HttpWebRequest.EndGetRequestStream (IAsyncResult asyncResult) [0
x00000] in <filename unknown>:0
  at System.Net.HttpWebRequest.GetRequestStream () [0x00000] in <filename unknow
n>:0
  at dynmap.core.Dynmap.Load () [0x00000] in <filename unknown>:0
  at Rocket.Core.Plugins.RocketPlugin.LoadPlugin () [0x00000] in <filename unkno
wn>:0

[unloading] Dynmap
`
