### ISSUE TITLE
Dynmap not connecting to php.

### ISSUE THREAD

**Issue by Alec123445** [AnthoDingo/DynmapSource#13]
![image](https://cloud.githubusercontent.com/assets/18058634/16401133/9a0ce310-3c96-11e6-81c4-22a1b4255fbf.png)
Php server is running and configured correctly. If you could point out what you think I might be wrong.
thanks
running on the build you made for unturned i found on LinhyCZ Dynmap issues.

**Comment by AnthoDingo** [comment]
Can you copy/paste your dynmap config files ? (plugins and web)

**Comment by Alec123445** [comment]
I have fixed it. In the Dynmap.configuration I had 
  <WebCoreAddress>http://192.168.1.101:888</WebCoreAddress>
And i fixed it by adding the /
  <WebCoreAddress>http://192.168.1.101:888/</WebCoreAddress>
I also completely wiped my php server and started clean but i was still encountering this issue till i added / to the end of the address
I am horrible.
Sorry for wasting your time.

Thanks,
Alec
