### ISSUE TITLE
Simplify js script

### ISSUE THREAD

**Issue by AnthoDingo** [AnthoDingo/DynmapSource#5]
Remove basic js.
Replace by jQuery.

**Comment by Alec123445** [comment]
is it fixed?

**Comment by Alec123445** [comment]
[loading] Dynmap
Dynmap >> Loading ...
Dynmap >> Finding map : D:\Desktop\SteamCmd\steamapps\common\unturned\Maps\Alpha Valley
Dynmap >> Finding map : D:\Desktop\SteamCmd\steamapps\common\unturned\Maps\Monolith
Dynmap >> Finding map : D:\Desktop\SteamCmd\steamapps\common\unturned\Maps\PEI
Dynmap >> Finding map : D:\Desktop\SteamCmd\steamapps\common\unturned\Maps\PEI Arena
Dynmap >> Finding map : D:\Desktop\SteamCmd\steamapps\common\unturned\Maps\Tutorial
Dynmap >> Finding map : D:\Desktop\SteamCmd\steamapps\common\unturned\Maps\Washington
Dynmap >> Finding map : D:\Desktop\SteamCmd\steamapps\common\unturned\Maps\Washington Arena
Dynmap >> Finding map : D:\Desktop\SteamCmd\steamapps\common\unturned\Maps\Yukon
Failed to load Dynmap, unloading now... :System.Net.WebException: The remote server returned an error: (404) Not Found.
  at System.Net.HttpWebRequest.CheckFinalStatus (System.Net.WebAsyncResult result) [0x00000] in <filename unknown>:0
  at System.Net.HttpWebRequest.SetResponseData (System.Net.WebConnectionData data) [0x00000] in <filename unknown>:0

[unloading] Dynmap

**Comment by AnthoDingo** [comment]
Be patient, this is an open source project, not a company project?
Your log is not in relation with this issue.
