### ISSUE TITLE
Uploading maps to EasyPHP

### ISSUE THREAD

**Issue by Alec123445** [AnthoDingo/DynmapSource#6]
I read your readme and when you put a new version up i start new on the web side. Im going to move the map.pngs over but how do you configure EasyPHP to increase allowed transfer file size?

**Comment by AnthoDingo** [comment]
Refer to EasyPHP manual.
I'm not responding of your webserver/php installation.

**Comment by Alec123445** [comment]
Ok

**Comment by Alec123445** [comment]
Found it.

**Comment by Alec123445** [comment]
Might want to add this into the readme http://php.net/upload-max-filesize

**Comment by AnthoDingo** [comment]
It's in :
![image](https://cloud.githubusercontent.com/assets/4434864/15913221/f079e6ca-2dd8-11e6-85c7-b532dcf8779f.png)
