### ISSUE TITLE
Map resizing required to fix player position

### ISSUE THREAD

**Issue by Alec123445** [AnthoDingo/DynmapSource#9]
@AnthoDingo 
All the players were clumped into the middle of the map like this. On a 4096x4096
![image](https://cloud.githubusercontent.com/assets/18058634/15913241/9b4c0282-2d8d-11e6-9d8f-db2ff0dd870a.png)
I fixed it by resizing it to 2048x2048.

**Comment by AnthoDingo** [comment]
Try pull last commit https://github.com/AnthoDingo/DynmapSource/commit/0ea18ce4a95d5d63e840247641ceb5e397a2f575

**Comment by Alec123445** [comment]
@AnthoDingo When you have code or ^^ in a response is this for you to reference in the future?

**Comment by AnthoDingo** [comment]
As mention pull the commit https://github.com/AnthoDingo/DynmapSource/commit/0ea18ce4a95d5d63e840247641ceb5e397a2f575

STOP to ask me to code.
This is an open source project i work on it when I've the time.
I'm not your slave.

**Comment by Alec123445** [comment]
I understand. I was not trying to force you to code, i am sorry I was not clear with my intentions. I have limited time as well. I was asking when you post the code in an issue is that for future reference? Because I am incompetent and can't interprate it well.  I stress that i am trying to be patient im a impatient person and for this i am sorry. I am just trying to provide info on problems that I am having so that you can determine problems and hopefully by being saturated with info you might be able to code more efficiently. To be able to know what problems are happening so you can decide what to fix.

**Comment by Alec123445** [comment]
What would you like me to do when i come across a problem. Post new issues? Wait for the next build when you get to it? I am very sorry that i have been annoying you that was not my intention. And yes this is open source being worked on by one person i was expecting to much.  I am 14 and still finding my way. So i am sorry.

**Comment by AnthoDingo** [comment]
Please send me original map.png

**Comment by Alec123445** [comment]
![image](http://i.imgur.com/nuug0aI.jpg) i could not attach it directly http://i.imgur.com/nuug0aI.jpg
http://steamcommunity.com/sharedfiles/filedetails/?id=611518943&searchtext=canada+%2B
